apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: blue-green-test
  name: internal-microservices
  namespace: ms-blue-green
spec:
  ingressClassName: internal-microservices
  rules:
  - host: blue-green-test.ms.qa
    http:
      paths:
      - backend:
          service:
            name: blue-green-test
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
